#!/usr/bin/python
import matplotlib               
import numpy as np                  
from pylab import *
from matplotlib import pyplot as pl
#from matplotlib import axis as ax
from matplotlib.ticker import MultipleLocator#, FormatStrFormatter
from matplotlib.backends.backend_pdf import PdfPages
#pp = PdfPages('plots/130729_Hopkins_shifted_df_DF.pdf')
pp = PdfPages('plots/130807_Hopkins_shifted_dF_propto_wo.pdf')

coeff = 0.159 # in eV. (2.41*1e14) # in rad/s
n = arange(0,500)
z = n * coeff

x_nopeak,y_nopeak=np.loadtxt('data/Y23605L.txt'  , unpack=True, usecols = [0,1])

eiz_npk_or = np.loadtxt('data/eiz_nopeak.txt'  , unpack=True, usecols = [0])
eiz_042_or = np.loadtxt('data/eiz_042_peak.txt', unpack=True, usecols = [0])
eiz_062_or = np.loadtxt('data/eiz_062_peak.txt', unpack=True, usecols = [0])
eiz_082_or = np.loadtxt('data/eiz_082_peak.txt', unpack=True, usecols = [0])
eiz_102_or = np.loadtxt('data/eiz_102_peak.txt', unpack=True, usecols = [0])
eiz_132_or = np.loadtxt('data/eiz_132_peak.txt', unpack=True, usecols = [0])
eiz_182_or = np.loadtxt('data/eiz_182_peak.txt', unpack=True, usecols = [0])
Aiz_npk_or = np.loadtxt('data/Aiz_or_npk.txt', unpack=True, usecols = [0])
Aiz_042_or = np.loadtxt('data/Aiz_or_042.txt', unpack=True, usecols = [0])
Aiz_062_or = np.loadtxt('data/Aiz_or_062.txt', unpack=True, usecols = [0])
Aiz_082_or = np.loadtxt('data/Aiz_or_082.txt', unpack=True, usecols = [0])
Aiz_102_or = np.loadtxt('data/Aiz_or_102.txt', unpack=True, usecols = [0])
Aiz_132_or = np.loadtxt('data/Aiz_or_132.txt', unpack=True, usecols = [0])
Aiz_182_or = np.loadtxt('data/Aiz_or_182.txt', unpack=True, usecols = [0])
dAiz_042_or = np.loadtxt('data/dAiz_or_042.txt', unpack=True, usecols = [0])
dAiz_062_or = np.loadtxt('data/dAiz_or_062.txt', unpack=True, usecols = [0])
dAiz_082_or = np.loadtxt('data/dAiz_or_082.txt', unpack=True, usecols = [0])
dAiz_102_or = np.loadtxt('data/dAiz_or_102.txt', unpack=True, usecols = [0])
dAiz_132_or = np.loadtxt('data/dAiz_or_132.txt', unpack=True, usecols = [0])
dAiz_182_or = np.loadtxt('data/dAiz_or_182.txt', unpack=True, usecols = [0])

eiz_npk_m0 = np.loadtxt('data/eiz_npk_meas.txt'  , unpack=True, usecols = [0])
eiz_042_m0 = np.loadtxt('data/eiz_042_meas.txt', unpack=True, usecols = [0])
eiz_062_m0 = np.loadtxt('data/eiz_062_meas.txt', unpack=True, usecols = [0])
eiz_082_m0 = np.loadtxt('data/eiz_082_meas.txt', unpack=True, usecols = [0])
eiz_102_m0 = np.loadtxt('data/eiz_102_meas.txt', unpack=True, usecols = [0])
eiz_132_m0 = np.loadtxt('data/eiz_132_meas.txt', unpack=True, usecols = [0])
eiz_182_m0 = np.loadtxt('data/eiz_182_meas.txt', unpack=True, usecols = [0])
Aiz_npk_m0 = np.loadtxt('data/Aiz_m0_npk.txt', unpack=True, usecols = [0])
Aiz_042_m0 = np.loadtxt('data/Aiz_m0_042.txt', unpack=True, usecols = [0])
Aiz_062_m0 = np.loadtxt('data/Aiz_m0_062.txt', unpack=True, usecols = [0])
Aiz_082_m0 = np.loadtxt('data/Aiz_m0_082.txt', unpack=True, usecols = [0])
Aiz_102_m0 = np.loadtxt('data/Aiz_m0_102.txt', unpack=True, usecols = [0])
Aiz_132_m0 = np.loadtxt('data/Aiz_m0_132.txt', unpack=True, usecols = [0])
Aiz_182_m0 = np.loadtxt('data/Aiz_m0_182.txt', unpack=True, usecols = [0])
dAiz_042_m0 = np.loadtxt('data/dAiz_m0_042.txt', unpack=True, usecols = [0])
dAiz_062_m0 = np.loadtxt('data/dAiz_m0_062.txt', unpack=True, usecols = [0])
dAiz_082_m0 = np.loadtxt('data/dAiz_m0_082.txt', unpack=True, usecols = [0])
dAiz_102_m0 = np.loadtxt('data/dAiz_m0_102.txt', unpack=True, usecols = [0])
dAiz_132_m0 = np.loadtxt('data/dAiz_m0_132.txt', unpack=True, usecols = [0])
dAiz_182_m0 = np.loadtxt('data/dAiz_m0_182.txt', unpack=True, usecols = [0])

eiz_npk_m1 = np.loadtxt('data/eiz_npk_meas1.txt'  , unpack=True, usecols = [0])
eiz_042_m1 = np.loadtxt('data/eiz_042_meas1.txt', unpack=True, usecols = [0])
eiz_062_m1 = np.loadtxt('data/eiz_062_meas1.txt', unpack=True, usecols = [0])
eiz_082_m1 = np.loadtxt('data/eiz_082_meas1.txt', unpack=True, usecols = [0])
eiz_102_m1 = np.loadtxt('data/eiz_102_meas1.txt', unpack=True, usecols = [0])
eiz_132_m1 = np.loadtxt('data/eiz_132_meas1.txt', unpack=True, usecols = [0])
eiz_182_m1 = np.loadtxt('data/eiz_182_meas1.txt', unpack=True, usecols = [0])
Aiz_npk_m1 = np.loadtxt('data/Aiz_m1_npk.txt', unpack=True, usecols = [0])
Aiz_042_m1 = np.loadtxt('data/Aiz_m1_042.txt', unpack=True, usecols = [0])
Aiz_062_m1 = np.loadtxt('data/Aiz_m1_062.txt', unpack=True, usecols = [0])
Aiz_082_m1 = np.loadtxt('data/Aiz_m1_082.txt', unpack=True, usecols = [0])
Aiz_102_m1 = np.loadtxt('data/Aiz_m1_102.txt', unpack=True, usecols = [0])
Aiz_132_m1 = np.loadtxt('data/Aiz_m1_132.txt', unpack=True, usecols = [0])
Aiz_182_m1 = np.loadtxt('data/Aiz_m1_182.txt', unpack=True, usecols = [0])
dAiz_042_m1 = np.loadtxt('data/dAiz_m1_042.txt', unpack=True, usecols = [0])
dAiz_062_m1 = np.loadtxt('data/dAiz_m1_062.txt', unpack=True, usecols = [0])
dAiz_082_m1 = np.loadtxt('data/dAiz_m1_082.txt', unpack=True, usecols = [0])
dAiz_102_m1 = np.loadtxt('data/dAiz_m1_102.txt', unpack=True, usecols = [0])
dAiz_132_m1 = np.loadtxt('data/dAiz_m1_132.txt', unpack=True, usecols = [0])
dAiz_182_m1 = np.loadtxt('data/dAiz_m1_182.txt', unpack=True, usecols = [0])

eiz_npk_m2 = np.loadtxt('data/eiz_npk_meas2.txt'  , unpack=True, usecols = [0])
eiz_042_m2 = np.loadtxt('data/eiz_042_meas2.txt', unpack=True, usecols = [0])
eiz_062_m2 = np.loadtxt('data/eiz_062_meas2.txt', unpack=True, usecols = [0])
eiz_082_m2 = np.loadtxt('data/eiz_082_meas2.txt', unpack=True, usecols = [0])
eiz_102_m2 = np.loadtxt('data/eiz_102_meas2.txt', unpack=True, usecols = [0])
eiz_132_m2 = np.loadtxt('data/eiz_132_meas2.txt', unpack=True, usecols = [0])
eiz_182_m2 = np.loadtxt('data/eiz_182_meas2.txt', unpack=True, usecols = [0])
Aiz_npk_m2 = np.loadtxt('data/Aiz_m2_npk.txt', unpack=True, usecols = [0])
Aiz_042_m2 = np.loadtxt('data/Aiz_m2_042.txt', unpack=True, usecols = [0])
Aiz_062_m2 = np.loadtxt('data/Aiz_m2_062.txt', unpack=True, usecols = [0])
Aiz_082_m2 = np.loadtxt('data/Aiz_m2_082.txt', unpack=True, usecols = [0])
Aiz_102_m2 = np.loadtxt('data/Aiz_m2_102.txt', unpack=True, usecols = [0])
Aiz_132_m2 = np.loadtxt('data/Aiz_m2_132.txt', unpack=True, usecols = [0])
Aiz_182_m2 = np.loadtxt('data/Aiz_m2_182.txt', unpack=True, usecols = [0])
dAiz_042_m2 = np.loadtxt('data/dAiz_m2_042.txt', unpack=True, usecols = [0])
dAiz_062_m2 = np.loadtxt('data/dAiz_m2_062.txt', unpack=True, usecols = [0])
dAiz_082_m2 = np.loadtxt('data/dAiz_m2_082.txt', unpack=True, usecols = [0])
dAiz_102_m2 = np.loadtxt('data/dAiz_m2_102.txt', unpack=True, usecols = [0])
dAiz_132_m2 = np.loadtxt('data/dAiz_m2_132.txt', unpack=True, usecols = [0])
dAiz_182_m2 = np.loadtxt('data/dAiz_m2_182.txt', unpack=True, usecols = [0])

pl.figure()
pl.plot(n,eiz_npk_or, color='b')
pl.plot(n,eiz_042_or, color='c')
pl.plot(n,eiz_062_or, color='r')
pl.plot(n,eiz_082_or, color='g')
pl.plot(n,eiz_102_or, color='m')
pl.plot(n,eiz_132_or, color='y')
pl.plot(n,eiz_182_or, color='k')

pl.plot(n,eiz_npk_m0, linestyle = '--', color='b')
pl.plot(n,eiz_042_m0, linestyle = '--', color='c')
pl.plot(n,eiz_062_m0, linestyle = '--', color='r')
pl.plot(n,eiz_082_m0, linestyle = '--', color='g')
pl.plot(n,eiz_102_m0, linestyle = '--', color='m')
pl.plot(n,eiz_132_m0, linestyle = '--', color='y')
pl.plot(n,eiz_182_m0, linestyle = '--', color='k')

pl.plot(n,eiz_npk_m1, linestyle = '--', color='b')
pl.plot(n,eiz_042_m1, linestyle = '--', color='c')
pl.plot(n,eiz_062_m1, linestyle = '--', color='r')
pl.plot(n,eiz_082_m1, linestyle = '--', color='g')
pl.plot(n,eiz_102_m1, linestyle = '--', color='m')
pl.plot(n,eiz_132_m1, linestyle = '--', color='y')
pl.plot(n,eiz_182_m1, linestyle = '--', color='k')

pl.plot(n,eiz_npk_m2, linestyle = '--', color='b')
pl.plot(n,eiz_042_m2, linestyle = '--', color='c')
pl.plot(n,eiz_062_m2, linestyle = '--', color='r')
pl.plot(n,eiz_082_m2, linestyle = '--', color='g')
pl.plot(n,eiz_102_m2, linestyle = '--', color='m')
pl.plot(n,eiz_132_m2, linestyle = '--', color='y')
pl.plot(n,eiz_182_m2, linestyle = '--', color='k')

pl.axis([0,120,1.3,2.7])
pl.xlabel(r'$N$', size = 21)
pl.ylabel(r'$\varepsilon\mathrm{(i\zeta_{N})/k _{B} T}$', size = 21)
pl.savefig('plots/eiz_sigma10.png', dpi = 300)

pl.figure()
pl.plot(n,Aiz_npk_or, color='b')
pl.plot(n,Aiz_042_or, color='c')
pl.plot(n,Aiz_062_or, color='r')
pl.plot(n,Aiz_082_or, color='g')
pl.plot(n,Aiz_102_or, color='m')
pl.plot(n,Aiz_132_or, color='y')
pl.plot(n,Aiz_182_or, color='k')

pl.plot(n,Aiz_npk_m0, linestyle = '--', color='b')
pl.plot(n,Aiz_042_m0, linestyle = '--', color='c')
pl.plot(n,Aiz_062_m0, linestyle = '--', color='r')
pl.plot(n,Aiz_082_m0, linestyle = '--', color='g')
pl.plot(n,Aiz_102_m0, linestyle = '--', color='m')
pl.plot(n,Aiz_132_m0, linestyle = '--', color='y')
pl.plot(n,Aiz_182_m0, linestyle = '--', color='k')

pl.plot(n,Aiz_npk_m1, linestyle = '--', color='b')
pl.plot(n,Aiz_042_m1, linestyle = '--', color='c')
pl.plot(n,Aiz_062_m1, linestyle = '--', color='r')
pl.plot(n,Aiz_082_m1, linestyle = '--', color='g')
pl.plot(n,Aiz_102_m1, linestyle = '--', color='m')
pl.plot(n,Aiz_132_m1, linestyle = '--', color='y')
pl.plot(n,Aiz_182_m1, linestyle = '--', color='k')

pl.plot(n,Aiz_npk_m2, linestyle = '--', color='b')
pl.plot(n,Aiz_042_m2, linestyle = '--', color='c')
pl.plot(n,Aiz_062_m2, linestyle = '--', color='r')
pl.plot(n,Aiz_082_m2, linestyle = '--', color='g')
pl.plot(n,Aiz_102_m2, linestyle = '--', color='m')
pl.plot(n,Aiz_132_m2, linestyle = '--', color='y')
pl.plot(n,Aiz_182_m2, linestyle = '--', color='k')

pl.axis([0,120,0.025,0.23])
pl.xlabel(r'$N$', size = 21)
pl.ylabel(r'$\mathcal{A}\mathrm{(i\zeta_{N})/k _{B} T}$', size = 21)
pl.savefig('plots/Aiz_sigma10.png', dpi = 300)

pl.figure()
pl.plot(n,dAiz_042_or, color='c')
pl.plot(n,dAiz_062_or, color='r')
pl.plot(n,dAiz_082_or, color='g')
pl.plot(n,dAiz_102_or, color='m')
pl.plot(n,dAiz_132_or, color='y')
pl.plot(n,dAiz_182_or, color='k')

pl.plot(n,dAiz_042_m0, linestyle = '--', color='c')
pl.plot(n,dAiz_062_m0, linestyle = '--', color='r')
pl.plot(n,dAiz_082_m0, linestyle = '--', color='g')
pl.plot(n,dAiz_102_m0, linestyle = '--', color='m')
pl.plot(n,dAiz_132_m0, linestyle = '--', color='y')
pl.plot(n,dAiz_182_m0, linestyle = '--', color='k')

pl.plot(n,dAiz_042_m1, linestyle = '-.', color='c')
pl.plot(n,dAiz_062_m1, linestyle = '-.', color='r')
pl.plot(n,dAiz_082_m1, linestyle = '-.', color='g')
pl.plot(n,dAiz_102_m1, linestyle = '-.', color='m')
pl.plot(n,dAiz_132_m1, linestyle = '-.', color='y')
pl.plot(n,dAiz_182_m1, linestyle = '-.', color='k')

pl.plot(n,dAiz_042_m2, linestyle = ':', color='c')
pl.plot(n,dAiz_062_m2, linestyle = ':', color='r')
pl.plot(n,dAiz_082_m2, linestyle = ':', color='g')
pl.plot(n,dAiz_102_m2, linestyle = ':', color='m')
pl.plot(n,dAiz_132_m2, linestyle = ':', color='y')
pl.plot(n,dAiz_182_m2, linestyle = ':', color='k')

pl.axis([0,120,-0.002,0.08])
pl.xlabel(r'$N$', size = 21)
pl.ylabel(r'$\delta\mathcal{A}\mathrm{(i\zeta_{N})/k _{B} T}$', size = 21)
pl.savefig('plots/dAiz_sigma10.png', dpi = 300)
pl.show()
pl.close()
